use crate::error::{Result, SymConflictError};
use std::fs::{self, File};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Debug, Clone)]
pub struct PrefixConfig {
    pub prefix: String,
    pub symbols: Vec<SymbolTarget>,
    pub output_dir: PathBuf,
    pub target_binary: PathBuf,
    pub method: InjectMethod,
}

#[derive(Debug, Clone)]
pub struct SymbolTarget {
    pub name: String,
    pub library: PathBuf,
    pub is_function: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InjectMethod {
    LdWrap,
    VersionScript,
    Both,
}

impl Default for InjectMethod {
    fn default() -> Self {
        InjectMethod::LdWrap
    }
}

pub struct PrefixInjector {
    config: PrefixConfig,
}

impl PrefixInjector {
    pub fn new(config: PrefixConfig) -> Self {
        PrefixInjector { config }
    }

    pub fn execute(&self) -> Result<()> {
        println!("开始符号前缀注入...");
        println!("前缀: {}", self.config.prefix);
        println!("目标符号数: {}", self.config.symbols.len());
        println!("输出目录: {}", self.config.output_dir.display());

        fs::create_dir_all(&self.config.output_dir)?;

        match self.config.method {
            InjectMethod::LdWrap => self.inject_ld_wrap()?,
            InjectMethod::VersionScript => self.inject_version_script()?,
            InjectMethod::Both => {
                self.inject_ld_wrap()?;
                self.inject_version_script()?;
            }
        }

        Ok(())
    }

    fn inject_ld_wrap(&self) -> Result<()> {
        println!("\n使用ld --wrap方法...");

        let wrapper_c_path = self.config.output_dir.join("symbol_wrapper.c");
        let linker_script_path = self.config.output_dir.join("wrap_symbols.ld");
        let wrapper_so_path = self.config.output_dir.join("libsymbol_wrapper.so");

        self.generate_wrapper_c(&wrapper_c_path)?;
        self.generate_ld_script(&linker_script_path)?;
        self.compile_wrapper(&wrapper_c_path, &wrapper_so_path)?;

        if self.config.target_binary.exists() {
            self.relink_binary(&wrapper_so_path, &linker_script_path)?;
        }

        Ok(())
    }

    fn generate_wrapper_c(&self, output_path: &Path) -> Result<()> {
        let mut file = File::create(output_path)?;

        writeln!(file, "/* Generated by symconflict - Symbol Wrapper */")?;
        writeln!(file, "#include <stdio.h>")?;
        writeln!(file, "#include <stdlib.h>")?;
        writeln!(file, "#include <dlfcn.h>")?;
        writeln!(file, "")?;

        for symbol in &self.config.symbols {
            let prefixed_name = format!("{}{}", self.config.prefix, symbol.name);
            let real_name = format!("__real_{}", symbol.name);

            if symbol.is_function {
                writeln!(file, "/* Wrapper for {} */", symbol.name)?;
                writeln!(file, "void* {}_original = NULL;", symbol.name)?;
                writeln!(file, "")?;
                writeln!(file, "void* __wrap_{}(void) {{", symbol.name)?;
                writeln!(file, "    if (!{}_original) {{", symbol.name)?;
                writeln!(file, "        {}_original = dlsym(RTLD_NEXT, \"{}\");", symbol.name, symbol.name)?;
                writeln!(file, "        if (!{}_original) {{", symbol.name)?;
                writeln!(file, "            fprintf(stderr, \"symconflict: Could not find original {}\\n\");", symbol.name)?;
                writeln!(file, "            abort();")?;
                writeln!(file, "        }}")?;
                writeln!(file, "    }}")?;
                writeln!(file, "    return {}_original;", symbol.name)?;
                writeln!(file, "}}")?;
                writeln!(file, "")?;

                writeln!(file, "/* Prefixed alias: {} */", prefixed_name)?;
                writeln!(file, "void* {}(void) __attribute__((alias(\"__wrap_{}\")));", prefixed_name, symbol.name)?;
                writeln!(file, "")?;
            } else {
                writeln!(file, "/* Variable wrapper for {} */", symbol.name)?;
                writeln!(file, "void* {}_var_ptr = NULL;", symbol.name)?;
                writeln!(file, "extern __typeof__({0}) {0} __attribute__((alias(\"{1}{0}\")));", symbol.name, self.config.prefix)?;
                writeln!(file, "")?;
            }
        }

        writeln!(file, "/* Library constructor */")?;
        writeln!(file, "__attribute__((constructor))")?;
        writeln!(file, "static void symconflict_init(void) {{")?;
        writeln!(file, "    fprintf(stderr, \"[symconflict] Symbol wrapper loaded\\n\");")?;
        for symbol in &self.config.symbols {
            writeln!(file, "    {}_original = dlsym(RTLD_NEXT, \"{}\");", symbol.name, symbol.name)?;
        }
        writeln!(file, "}}")?;

        println!("  生成包装代码: {}", output_path.display());
        Ok(())
    }

    fn generate_ld_script(&self, output_path: &Path) -> Result<()> {
        let mut file = File::create(output_path)?;

        writeln!(file, "/* Generated by symconflict - Linker Script for --wrap */")?;
        writeln!(file, "")?;

        for symbol in &self.config.symbols {
            writeln!(file, "--wrap={}", symbol.name)?;
        }

        writeln!(file, "")?;
        writeln!(file, "VERSION {{")?;
        writeln!(file, "    SYMCONFLICT {{")?;
        for symbol in &self.config.symbols {
            writeln!(file, "        {};", symbol.name)?;
            writeln!(file, "        {}{};", self.config.prefix, symbol.name)?;
        }
        writeln!(file, "    }};")?;
        writeln!(file, "}}")?;

        println!("  生成链接器脚本: {}", output_path.display());
        Ok(())
    }

    fn compile_wrapper(&self, c_path: &Path, so_path: &Path) -> Result<()> {
        println!("  编译wrapper库...");

        let cc = std::env::var("CC").unwrap_or_else(|_| "gcc".to_string());

        let output = Command::new(&cc)
            .args([
                "-shared",
                "-fPIC",
                "-o",
                so_path.to_str().unwrap(),
                c_path.to_str().unwrap(),
                "-ldl",
            ])
            .output()?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(SymConflictError::CommandExecution(format!(
                "编译wrapper库失败:\n{}",
                stderr
            )));
        }

        println!("  Wrapper库编译成功: {}", so_path.display());
        Ok(())
    }

    fn inject_version_script(&self) -> Result<()> {
        println!("\n使用Symbol Version Script方法...");

        let version_script_path = self.config.output_dir.join("symbol_versions.map");
        let wrapper_c_path = self.config.output_dir.join("version_wrapper.c");
        let wrapper_so_path = self.config.output_dir.join("libversion_wrapper.so");

        self.generate_version_script(&version_script_path)?;
        self.generate_version_wrapper_c(&wrapper_c_path)?;
        self.compile_with_version_script(&wrapper_c_path, &version_script_path, &wrapper_so_path)?;

        Ok(())
    }

    fn generate_version_script(&self, output_path: &Path) -> Result<()> {
        let mut file = File::create(output_path)?;

        writeln!(file, "/* Generated by symconflict - Version Script */")?;
        writeln!(file, "VERSION {{")?;
        writeln!(file, "    global:")?;

        for symbol in &self.config.symbols {
            writeln!(file, "        {}{};", self.config.prefix, symbol.name)?;
        }

        writeln!(file, "")?;
        writeln!(file, "    local:")?;
        for symbol in &self.config.symbols {
            writeln!(file, "        {};", symbol.name)?;
        }
        writeln!(file, "        *;")?;
        writeln!(file, "}};")?;

        println!("  生成版本脚本: {}", output_path.display());
        Ok(())
    }

    fn generate_version_wrapper_c(&self, output_path: &Path) -> Result<()> {
        let mut file = File::create(output_path)?;

        writeln!(file, "/* Generated by symconflict - Version Wrapper */")?;
        writeln!(file, "#include <stdio.h>")?;
        writeln!(file, "#include <dlfcn.h>")?;
        writeln!(file, "")?;

        for symbol in &self.config.symbols {
            let prefixed_name = format!("{}{}", self.config.prefix, symbol.name);

            writeln!(file, "/* {} -> {} */", symbol.name, prefixed_name)?;

            if symbol.is_function {
                writeln!(file, "void* {}(void) {{", prefixed_name)?;
                writeln!(file, "    static void* (*real_func)(void) = NULL;")?;
                writeln!(file, "    if (!real_func) {{")?;
                writeln!(file, "        real_func = dlsym(RTLD_NEXT, \"{}\");", symbol.name)?;
                writeln!(file, "    }}")?;
                writeln!(file, "    return real_func ? real_func() : NULL;")?;
                writeln!(file, "}}")?;
            } else {
                writeln!(file, "void* {}_data = NULL;", prefixed_name)?;
                writeln!(file, "void* get_{}(void) {{", prefixed_name)?;
                writeln!(file, "    if (!{}_data) {{", prefixed_name)?;
                writeln!(file, "        {}_data = dlsym(RTLD_NEXT, \"{}\");", prefixed_name, symbol.name)?;
                writeln!(file, "    }}")?;
                writeln!(file, "    return {}_data;", prefixed_name)?;
                writeln!(file, "}}")?;
            }
            writeln!(file, "")?;
        }

        writeln!(file, "__asm__(\".symver {0}foo, {0}foo@@MYVERSION\");", self.config.prefix)?;

        println!("  生成版本包装代码: {}", output_path.display());
        Ok(())
    }

    fn compile_with_version_script(&self, c_path: &Path, script_path: &Path, so_path: &Path) -> Result<()> {
        println!("  使用版本脚本编译...");

        let cc = std::env::var("CC").unwrap_or_else(|_| "gcc".to_string());

        let output = Command::new(&cc)
            .args([
                "-shared",
                "-fPIC",
                "-Wl,--version-script",
                script_path.to_str().unwrap(),
                "-o",
                so_path.to_str().unwrap(),
                c_path.to_str().unwrap(),
                "-ldl",
            ])
            .output()?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(SymConflictError::CommandExecution(format!(
                "编译版本wrapper失败:\n{}",
                stderr
            )));
        }

        println!("  Version wrapper编译成功: {}", so_path.display());
        Ok(())
    }

    fn relink_binary(&self, wrapper_so: &Path, ld_script: &Path) -> Result<()> {
        println!("\n重新链接目标二进制...");

        let backup_path = self.config.target_binary.with_extension("original");
        if !backup_path.exists() {
            fs::copy(&self.config.target_binary, &backup_path)?;
            println!("  原始文件已备份: {}", backup_path.display());
        }

        println!("  警告: 自动重新链接需要原始编译命令和目标文件");
        println!("  建议手动重新链接:");
        println!("  gcc [...] -Wl,--wrap=symbol1,--wrap=symbol2 -L{} -lsymbol_wrapper", 
                 self.config.output_dir.display());
        println!("");
        println!("  或者在运行时预加载:");
        println!("  LD_PRELOAD={} ./{}", wrapper_so.display(), self.config.target_binary.display());

        self.generate_makefile_snippet()?;

        Ok(())
    }

    fn generate_makefile_snippet(&self) -> Result<()> {
        let makefile_path = self.config.output_dir.join("Makefile.snippet");
        let mut file = File::create(&makefile_path)?;

        writeln!(file, "# Generated by symconflict - Makefile snippet")?;
        writeln!(file, "SYMCONFLICT_DIR := {}", self.config.output_dir.display())?;
        writeln!(file, "SYMCONFLICT_LIB := -L$(SYMCONFLICT_DIR) -lsymbol_wrapper")?;
        writeln!(file, "SYMCONFLICT_LDFLAGS := \\")?;
        for symbol in &self.config.symbols {
            writeln!(file, "    -Wl,--wrap={} \\", symbol.name)?;
        }
        writeln!(file, "")?;
        writeln!(file, "# Usage:")?;
        writeln!(file, "# LDFLAGS += $(SYMCONFLICT_LDFLAGS) $(SYMCONFLICT_LIB)")?;

        println!("  生成Makefile片段: {}", makefile_path.display());
        Ok(())
    }
}

pub fn list_conflicts_for_injection(conflicts: &[crate::conflict::SymbolConflict]) {
    println!("\n可用于前缀注入的冲突:");
    for (i, conflict) in conflicts.iter().enumerate() {
        println!("\n  [{}] {} ({}个库)", i + 1, conflict.base_name, conflict.conflicting_symbols.len());
        for sym in &conflict.conflicting_symbols {
            println!("      - {} (from {})", sym.name, sym.library.display());
        }
    }
}
