import os
import zipfile
import json
import uuid
from datetime import datetime
from typing import Dict, Any, List, Optional
from pathlib import Path

from config import settings


class XMindGenerator:
    def __init__(self):
        self.output_dir = settings.OUTPUT_DIR

    def _generate_id(self) -> str:
        return str(uuid.uuid4())

    def _create_topic(
        self,
        title: str,
        children: Optional[List[Dict[str, Any]]] = None,
        markers: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        topic = {
            "id": self._generate_id(),
            "title": title
        }

        if children:
            topic["children"] = {
                "attached": children
            }

        if markers:
            topic["markers"] = markers

        return topic

    def _build_xmind_content(
        self,
        title: str,
        decisions: List[str],
        todos: List[Dict[str, Any]],
        disputes: List[Dict[str, Any]],
        summary: str,
        speakers: List[str] = None,
        transcription: str = None
    ) -> Dict[str, Any]:
        root_children = []

        if summary:
            summary_children = [self._create_topic(summary)]
            root_children.append(self._create_topic("📝 会议摘要", summary_children))

        if decisions:
            decision_topics = [
                self._create_topic(d, markers=["fa-check"])
                for d in decisions
            ]
            root_children.append(self._create_topic("✅ 决策", decision_topics))

        if todos:
            todo_topics = []
            for todo in todos:
                task = todo.get("task", todo.get("content", "未命名任务"))
                assignee = todo.get("assignee", "未指定")
                deadline = todo.get("deadline", "未指定")
                priority = todo.get("priority", "medium")

                todo_children = [
                    self._create_topic(f"👤 负责人: {assignee}"),
                    self._create_topic(f"📅 截止日期: {deadline}")
                ]

                markers = []
                if priority == "high":
                    markers.append("priority-1")
                elif priority == "medium":
                    markers.append("priority-2")
                else:
                    markers.append("priority-3")

                todo_topics.append(self._create_topic(task, todo_children, markers))

            root_children.append(self._create_topic("📋 待办事项", todo_topics))

        if disputes:
            dispute_topics = []
            for dispute in disputes:
                issue = dispute.get("issue", "未命名争议")
                points = dispute.get("points", [])
                point_topics = [self._create_topic(p) for p in points]
                dispute_topics.append(self._create_topic(
                    f"⚖️ {issue}",
                    point_topics,
                    markers=["fa-flag"]
                ))

            root_children.append(self._create_topic("💬 争议点", dispute_topics))

        if speakers:
            speaker_topics = [self._create_topic(s) for s in speakers]
            root_children.append(self._create_topic("👥 参会人员", speaker_topics))

        if transcription:
            transcription_preview = transcription[:500] + "..." if len(transcription) > 500 else transcription
            root_children.append(self._create_topic(
                "📄 完整转录",
                [self._create_topic(transcription_preview)]
            ))

        root_topic = {
            "id": self._generate_id(),
            "title": title,
            "structureClass": "org.xmind.ui.map.unbalanced",
            "children": {
                "attached": root_children
            }
        }

        sheet = {
            "id": self._generate_id(),
            "class": "sheet",
            "title": "会议分析",
            "rootTopic": root_topic,
            "topicPositioning": "fixed",
            "theme": "simple"
        }

        return [sheet]

    def _create_metadata(self, title: str) -> Dict[str, Any]:
        return {
            "creator": {
                "name": "Meeting Analyzer",
                "version": "2.0"
            },
            "title": title,
            "description": "Generated by Meeting Analyzer with AI",
            "created": datetime.now().isoformat(),
            "updated": datetime.now().isoformat(),
            "tags": ["meeting", "analysis", "AI"]
        }

    def _create_manifest(self) -> str:
        return '''<?xml version="1.0" encoding="UTF-8"?>
<manifest xmlns="urn:xmind:xmap:xmlns:manifest:1.0">
  <file-entry full-path="" media-type="application/xmind"/>
  <file-entry full-path="content.json" media-type="application/json"/>
  <file-entry full-path="metadata.json" media-type="application/json"/>
  <file-entry full-path="META-INF/manifest.xml" media-type="application/xml"/>
</manifest>'''

    def _create_styles(self) -> Dict[str, Any]:
        return {
            "styles": [
                {
                    "id": "topic-style",
                    "type": "topic",
                    "properties": {
                        "svg:fill": "#ffffff",
                        "border-line-color": "#667eea",
                        "border-line-width": "1px",
                        "border-radius": "6px",
                        "line-color": "#667eea"
                    }
                }
            ]
        }

    def generate_xmind(
        self,
        meeting_id: int,
        title: str,
        decisions: List[str],
        todos: List[Dict[str, Any]],
        disputes: List[Dict[str, Any]],
        summary: str,
        speakers: List[str] = None,
        transcription: str = None
    ) -> str:
        safe_title = "".join(c for c in title if c.isalnum() or c in (' ', '-', '_')).rstrip()
        output_path = self.output_dir / f"meeting_{meeting_id}_{safe_title}.xmind"

        if output_path.exists():
            output_path.unlink()

        content_json = self._build_xmind_content(
            title, decisions, todos, disputes, summary, speakers, transcription
        )
        metadata_json = self._create_metadata(title)
        manifest_xml = self._create_manifest()
        styles_json = self._create_styles()

        with zipfile.ZipFile(output_path, 'w', zipfile.ZIP_DEFLATED) as zf:
            zf.writestr('content.json', json.dumps(content_json, ensure_ascii=False, indent=2))
            zf.writestr('metadata.json', json.dumps(metadata_json, ensure_ascii=False, indent=2))
            zf.writestr('styles.json', json.dumps(styles_json, ensure_ascii=False, indent=2))
            zf.writestr('META-INF/manifest.xml', manifest_xml)

            comments_json = [{
                "id": self._generate_id(),
                "author": "Meeting Analyzer",
                "time": datetime.now().isoformat(),
                "text": f"会议分析生成于 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
            }]
            zf.writestr('comments.json', json.dumps(comments_json, ensure_ascii=False, indent=2))

        print(f"XMind file generated: {output_path}")
        return str(output_path)

    def generate_xmind_markdown(
        self,
        meeting_id: int,
        title: str,
        decisions: List[str],
        todos: List[Dict[str, Any]],
        disputes: List[Dict[str, Any]],
        summary: str,
        speakers: List[str] = None
    ) -> str:
        safe_title = "".join(c for c in title if c.isalnum() or c in (' ', '-', '_')).rstrip()
        output_path = self.output_dir / f"meeting_{meeting_id}_{safe_title}.md"

        lines = [f"# {title}", ""]
        lines.append(f"_生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_")
        lines.append("")

        if summary:
            lines.extend(["## 📝 会议摘要", "", summary, ""])

        if decisions:
            lines.extend(["## ✅ 决策", ""])
            for d in decisions:
                lines.append(f"- [x] {d}")
            lines.append("")

        if todos:
            lines.extend(["## 📋 待办事项", ""])
            for todo in todos:
                task = todo.get("task", todo.get("content", "未命名任务"))
                assignee = todo.get("assignee", "未指定")
                deadline = todo.get("deadline", "未指定")
                priority = todo.get("priority", "medium")
                lines.append(f"- [ ] **{task}**")
                lines.append(f"  - 👤 负责人: {assignee}")
                lines.append(f"  - 📅 截止日期: {deadline}")
                lines.append(f"  - ⭐ 优先级: {priority}")
            lines.append("")

        if disputes:
            lines.extend(["## 💬 争议点", ""])
            for dispute in disputes:
                issue = dispute.get("issue", "未命名争议")
                points = dispute.get("points", [])
                lines.append(f"### ⚖️ {issue}")
                for p in points:
                    lines.append(f"- {p}")
                lines.append("")

        if speakers:
            lines.extend(["## 👥 参会人员", ""])
            for s in speakers:
                lines.append(f"- {s}")
            lines.append("")

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))

        return str(output_path)


xmind_generator = XMindGenerator()
