# Generated by Django 4.2.7 on 2026-05-17 03:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionresult',
            name='clearing_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='auctionresult',
            name='total_traded',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bid',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='node',
            name='current_generation',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='node',
            name='current_load',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='node',
            name='load_capacity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='node',
            name='solar_capacity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
