# Generated by Django 4.2.7 on 2026-05-17 03:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_auctionresult_clearing_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='battery_capacity',
            field=models.DecimalField(decimal_places=4, default=Decimal('10.0000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='node',
            name='battery_charge',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='node',
            name='battery_discharge',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='node',
            name='battery_efficiency',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.9000'), max_digits=5),
        ),
        migrations.AddField(
            model_name='node',
            name='battery_soc',
            field=models.DecimalField(decimal_places=4, default=Decimal('5.0000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='node',
            name='has_battery',
            field=models.BooleanField(default=True),
        ),
    ]
